EXPECTED_TYPES = {
    "date": [
        "date",
        "timestamp",
        "time",
        "created",
        "updated",
        "ordered",
        "order",
        "ship",
        "delivered",
        "transaction",
        "reported",
        "occurred",
        "event",
    ],
    "amount": [
        "sales",
        "price",
        "amount",
        "total",
        "cost",
        "profit",
        "revenue",
        "income",
        "quantity",
        "qty",
        "value",
        "balance",
    ],
    "category": [
        "category",
        "segment",
        "department",
        "class",
        "sub_category",
        "subcategory",
        "product",
        "item",
        "brand",
        "type",
        "group",
    ],
    "region": [
        "region",
        "state",
        "country",
        "city",
        "area",
        "zone",
        "territory",
        "location",
    ],
    "customer": [
        "customer",
        "client",
        "account",
        "user",
        "buyer",
    ],
}